ServerEvents.recipes(event => {

    event.recipes.gtceu.large_chemical_reactor('procnaqusulfate')
        .inputFluids(Fluid.of('gtceu:fluoroantimonic_acid 1000'))
        .itemInputs('3x gtceu:naquadria_sulfate_dust')
        .outputFluids('gtceu:processed_naquadria_sulfate 3105')
        .duration(700)
        .EUt((GTValues.VA[GTValues.LuV]))
    event.recipes.gtceu.large_chemical_reactor('acidprocnaqusulfate')
        .inputFluids('gtceu:sulfuric_acid 250', 'gtceu:processed_naquadria_sulfate 1000')
        .notConsumable('gtmutils:naquadah_credit')
        .outputFluids('gtceu:acidic_processed_naquadria_sulfate 3105')
        .duration(700)
        .EUt((GTValues.VA[GTValues.LuV]))
    event.recipes.gtceu.large_chemical_reactor('acidicfuelsolution')
        .inputFluids('gtceu:sulfuric_heavy_fuel 1500', 'gtceu:acidic_processed_naquadria_sulfate 1000')
        .notConsumable('gtceu:tiny_yttrium_dust')
        .outputFluids('gtceu:acidic_naquadria_fuel_solution 500')
        .duration(1000)
        .EUt((GTValues.VA[GTValues.LuV]))
    event.recipes.gtceu.large_chemical_reactor('impurenaqfuel')
        .inputFluids('gtceu:acidic_naquadria_fuel_solution 5000', 'gtceu:nitrobenzene 500')
        .itemInputs('gtceu:enriched_naquadah_sulfate_dust')
        .outputFluids('gtceu:impure_naquadria_fuel 5000')
        .duration(1000)
        .EUt((GTValues.VA[GTValues.LuV]))
    event.recipes.gtceu.centrifuge('purenaqfuel')
        .inputFluids('gtceu:impure_naquadria_fuel 250')
        .itemOutputsRanged('gtceu:resonant_naquadah_dust', 5, 15)
        .outputFluids('gtceu:pure_naquadria_fuel 250')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(1000)
        .EUt((GTValues.VA[GTValues.LuV]))
		
		//Plasmas
		
    event.recipes.gtceu.naquadahmk1('naquadriaplasma')
        .inputFluids('gtceu:pure_naquadria_fuel 5000', 'gtceu:helium_plasma 1500', 'gtceu:depleted_thorium_fuel 15000')
        .outputFluids('gtceu:naquadria_plasma_plasma 5000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UV]))
    event.recipes.gtceu.naquadahmk1('thoriumplasma')
        .inputFluids('gtceu:condensed_star_matter 5000', 'gtceu:naquadria_plasma_plasma 5000', 'gtceu:depleted_thorium_fuel 30000')
        .outputFluids('gtceu:thorium_plasma_plasma 10000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UHV]))
    event.recipes.gtceu.naquadahmk1('naquadriaplasmamk2')
        .inputFluids('gtceu:naquadria_fuel_mk2 5000', 'gtceu:thorium_plasma_plasma 5000', 'gtceu:stabilized_enriched_thorium_fuel 15000')
        .outputFluids('gtceu:naquadria_plasma_mk2_plasma 5000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UHV]))
    event.recipes.gtceu.naquadahmk2('thoriumplasma')
        .inputFluids('gtceu:naquadria 15000', 'gtceu:americium_plasma 5000', 'gtceu:stabilized_enriched_thorium_fuel 30000')
        .outputFluids('gtceu:thorium_plasma_plasma 20000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UHV]))
    event.recipes.gtceu.naquadahmk2('naquadriaplasmamk2')
        .inputFluids('gtceu:naquadria_fuel_mk2 5000', 'gtceu:thorium_plasma_plasma 7500', 'gtceu:stabilized_enriched_thorium_fuel 30000')
        .outputFluids('gtceu:naquadria_plasma_mk2_plasma 10000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UEV]))
	event.recipes.gtceu.naquadahmk2('naquadriaplasmamk3')
        .inputFluids('gtceu:naquadria_fuel_mk3 5000', 'gtceu:naquadria_plasma_mk2_plasma 5000', 'gtceu:meta_stable_hyper_enriched_thorium_fuel 30000')
        .outputFluids('gtceu:naquadria_plasma_mk3_plasma 10000')
        .duration(4200)
        .EUt((GTValues.VA[GTValues.UEV]))
		
		//Thorium Fuel Line
		
    event.recipes.gtceu.large_chemical_reactor('depletedthoriumfuel')
       .inputFluids('gtceu:nitrobenzene 10000')
	   .itemInputs('32x gtceu:thorium_dust')
       .outputFluids('gtceu:depleted_thorium_fuel 15000')
       .duration(1000)
       .EUt((GTValues.VA[GTValues.LuV]))
	event.recipes.gtceu.mixer('unstableenrichedthoriumfuel')
       .inputFluids('gtceu:depleted_thorium_fuel 30000', 'gtceu:radon 15000')
	   .itemInputs('16x gtceu:plutonium_241_dust', '32x gtceu:cadmium_dust','16x gtceu:cleaned_californium_dust')
       .outputFluids('gtceu:unstable_enriched_thorium_fuel 60000')
       .duration(2000)
       .EUt((GTValues.VA[GTValues.UV]))
	event.recipes.gtceu.extreme_cracking_unit('lightlyplasmacrackedunstableenrichedthoriumfuel')
       .inputFluids('gtceu:unstable_enriched_thorium_fuel 30000', 'gtceu:argon_plasma 5000')
	   .chancedInput('2x gtceu:neutron_reflector', 3333, 0)
	   .chancedInput('2x gtceu:neutron_reflector', 2500, 0)
	   .chancedInput('2x gtceu:neutron_reflector', 1111, 0)
       .outputFluids('gtceu:lightly_plasmacracked_unstable_enriched_thorium_fuel 15000')
       .duration(200)
       .EUt((GTValues.VA[GTValues.UV]))
	event.recipes.gtceu.extreme_cracking_unit('severlyplasmacrackedunstableenrichedthoriumfuel')
       .inputFluids('gtceu:unstable_enriched_thorium_fuel 30000', 'gtceu:iron_plasma 5000')
	   .chancedInput('2x gtceu:neutron_reflector', 5000, 0)
	   .chancedInput('2x gtceu:neutron_reflector', 2500, 0)
	   .chancedInput('2x gtceu:neutron_reflector', 1250, 0)
       .outputFluids('gtceu:severly_plasmacracked_unstable_enriched_thorium_fuel 15000')
       .duration(400)
       .EUt((GTValues.VA[GTValues.UHV]))
	event.recipes.gtceu.chemical_bath('hotstabilizedenrichedthoriumfuel')
       .inputFluids('gtceu:lightly_plasmacracked_unstable_enriched_thorium_fuel 30000')
	   .chancedInput('4x gtceu:gravi_star', 2500, 0)
       .outputFluids('gtceu:hot_stabilized_enriched_thorium_fuel 30000')
       .duration(2000)
       .EUt((GTValues.VA[GTValues.UV]))	   
	event.recipes.gtceu.vacuum_freezer('lqnitrogen')
       .inputFluids('gtceu:nitrogen 1000')
       .outputFluids('gtceu:liquid_nitrogen 1000')
       .duration(2400)
       .EUt((GTValues.VA[GTValues.LuV]))
	event.recipes.gtceu.vacuum_freezer('stabilizedenrichedthoriumfuel')
       .inputFluids('gtceu:hot_stabilized_enriched_thorium_fuel 10000','gtceu:liquid_nitrogen 10000')
       .outputFluids('gtceu:stabilized_enriched_thorium_fuel 10000')
       .duration(2400)
       .EUt((GTValues.VA[GTValues.UV]))
	event.recipes.gtceu.atomiccompressor('sdhog')
		.itemInputs('kubejs:quantum_energy_capsule')
		.inputFluids('gtceu:high_octane_gasoline 150000')
		.outputFluids('gtceu:super_dense_hog 15000')
		.duration(500)
		.EUt(GTValues.VA[GTValues.UHV]);
	 event.recipes.gtceu.large_chemical_reactor('veryunstablehyperenrichedthoriumfuel')
       .inputFluids('gtceu:severly_plasmacracked_unstable_enriched_thorium_fuel 15000', 'gtceu:super_dense_hog 15000', 'gtceu:sodium_potassium 25000')
	   .itemInputs('16x gtceu:teslarium_dust')
       .outputFluids('gtceu:very_unstable_hyper_enriched_thorium_fuel 60000')
       .duration(10000)
       .EUt((GTValues.VA[GTValues.UHV]))
	 event.recipes.gtceu.chemical_plant('hotmetastablehyperenrichedthoriumfuel')
		.notConsumable('kubejs:chemical_tier_four')
        .inputFluids('gtceu:very_unstable_hyper_enriched_thorium_fuel 20000','gtceu:hypoxylon 10000', 'gtceu:neutronium 5000')
        .outputFluids('gtceu:hot_meta_stable_hyper_enriched_thorium_fuel 20000')
        .circuit(20)
        .duration(50*20)
        .EUt(GTValues.VA[GTValues.UEV])
	 event.recipes.gtceu.vacuum_freezer('metastablehyperenrichedthoriumfuel')
       .inputFluids('gtceu:hot_meta_stable_hyper_enriched_thorium_fuel 10000','gtceu:liquid_nitrogen 10000')
       .outputFluids('gtceu:meta_stable_hyper_enriched_thorium_fuel 10000')
       .duration(2400)
       .EUt((GTValues.VA[GTValues.UHV]))
	   
		//Naquadria Fuel Line
		
	event.recipes.gtceu.large_chemical_reactor('enrichednaquadriafuelbase')
       .inputFluids('gtceu:pure_naquadria_fuel 15000', 'gtceu:depleted_thorium_fuel 15000', 'gtceu:diesel 20000')
       .outputFluids('gtceu:enriched_naquadria_fuel_base 20000')
       .duration(2000)
       .EUt((GTValues.VA[GTValues.UV]))
	event.recipes.gtceu.large_chemical_reactor('enrichednaquadriafuelbase2')
       .inputFluids('gtceu:pure_naquadria_fuel 15000', 'gtceu:depleted_thorium_fuel 15000', 'gtceu:cetane_boosted_diesel 20000')
       .outputFluids('gtceu:enriched_naquadria_fuel_base 40000')
       .duration(2000)
       .EUt((GTValues.VA[GTValues.UV]))
	event.recipes.gtceu.extreme_cracking_unit('lightlyplasmacrackedenrichednaquadriafuelbase')
       .inputFluids('gtceu:enriched_naquadria_fuel_base 20000', 'gtceu:oxygen_plasma 5000')
	   .chancedInput('2x gtceu:neutron_reflector', 3333, 0)
	   .chancedInput('2x gtceu:neutron_reflector', 2500, 0)
	   .chancedInput('2x gtceu:neutron_reflector', 1111, 0)
       .outputFluids('gtceu:lightly_plasmacracked_enriched_naquadria_fuel_base 10000')
       .duration(200)
       .EUt((GTValues.VA[GTValues.UHV]))
	event.recipes.gtceu.extreme_cracking_unit('severlyplasmacrackedenrichednaquadriafuelbase')
       .inputFluids('gtceu:enriched_naquadria_fuel_base 20000', 'gtceu:nickel_plasma 5000')
	   .chancedInput('2x gtceu:neutron_reflector', 7500, 0)
	   .chancedInput('2x gtceu:neutron_reflector', 5000, 0)
	   .chancedInput('2x gtceu:neutron_reflector', 2500, 0)
       .outputFluids('gtceu:severly_plasmacracked_enriched_naquadria_fuel_base 10000')
       .duration(400)
       .EUt((GTValues.VA[GTValues.UEV]))
	event.recipes.gtceu.distillation_tower('lightlyplasmacrackedenrichednaquadriafuelbase')
       .inputFluids('gtceu:lightly_plasmacracked_enriched_naquadria_fuel_base 1000')
       .outputFluids('gtceu:heavy_naquadria_fuel_waste 100', 'gtceu:heavy_naquadria_fuel 200', 'gtceu:light_naquadria_fuel_waste 100','gtceu:light_naquadria_fuel 500' ,'gtceu:enriched_naquadah_fuel_waste 100')
	   .cleanroom(CleanroomType.CLEANROOM)
       .duration(200)
       .EUt((GTValues.VA[GTValues.UV]))
	event.recipes.gtceu.distillation_tower('severlyplasmacrackedenrichednaquadriafuelbase')
       .inputFluids('gtceu:severly_plasmacracked_enriched_naquadria_fuel_base 1000')
       .outputFluids('gtceu:super_dense_naquadria_fuel 200', 'gtceu:heavy_naquadria_fuel_waste 100','gtceu:heavy_naquadria_fuel 500', 'gtceu:light_naquadria_fuel_waste 100' )
	   .cleanroom(CleanroomType.CLEANROOM)
       .duration(200)
       .EUt((GTValues.VA[GTValues.UV]))
    event.recipes.gtceu.centrifuge('enrichednaquadahfuelwaste')
        .inputFluids('gtceu:enriched_naquadah_fuel_waste 10000')
        .itemOutputsRanged('gtceu:enriched_naquadah_dust', 5, 15)
        .outputFluids('gtceu:enriched_naquadria_fuel_base 5000')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(1000)
        .EUt((GTValues.VA[GTValues.ZPM]))
    event.recipes.gtceu.centrifuge('lightnaquadriafuelwaste')
        .inputFluids('gtceu:light_naquadria_fuel_waste 10000')
        .itemOutputsRanged('gtceu:naquadria_dust', 5, 15)
        .outputFluids('gtceu:enriched_naquadria_fuel_base 25000', 'gtceu:light_naquadria_fuel 2500')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(1000)
        .EUt((GTValues.VA[GTValues.ZPM]))
	event.recipes.gtceu.centrifuge('heavynaquadriafuelwaste')
        .inputFluids('gtceu:heavy_naquadria_fuel_waste 10000')
        .itemOutputsRanged('gtceu:naquadria_dust', 15, 30)
        .outputFluids('gtceu:enriched_naquadria_fuel_base 25000', 'gtceu:heavy_naquadria_fuel 2500')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(1000)
        .EUt((GTValues.VA[GTValues.ZPM]))
	event.recipes.gtceu.mixer('treatedlightnaquadriafuel')
	   .itemInputs('56x gtceu:polyphenylene_sulfide_dust')
       .inputFluids('gtceu:light_naquadria_fuel 12500', 'gtceu:nitration_mixture 3000')
       .outputFluids('gtceu:treated_light_naquadria_fuel 18000')
	   .cleanroom(CleanroomType.CLEANROOM)
       .duration(2000)
       .EUt((GTValues.VA[GTValues.UV]))
	event.recipes.gtceu.mixer('treatedheavynaquadriafuel')
	   .itemInputs('48x gtceu:polybenzimidazole_dust')
       .inputFluids('gtceu:heavy_naquadria_fuel 10000', 'gtceu:sterilized_growth_medium 5000')
       .outputFluids('gtceu:treated_heavy_naquadria_fuel 18000')
	   .cleanroom(CleanroomType.CLEANROOM)
       .duration(2000)
       .EUt((GTValues.VA[GTValues.UHV]))
	event.recipes.gtceu.large_chemical_reactor('treatedsuperdensenaquadriafuel')
       .inputFluids('gtceu:super_dense_naquadria_fuel 5000', 'gtceu:antimatter 5000', 'gtceu:hypoxylon 5000')
       .outputFluids('gtceu:treated_super_dense_naquadria_fuel 15000')
	   .cleanroom(CleanroomType.STERILE_CLEANROOM)
       .duration(2000)
       .EUt((GTValues.VA[GTValues.UEV]))
	 event.recipes.gtceu.chemical_plant('naquadriafuelmixturemk2')
		.notConsumable('kubejs:chemical_tier_three')
        .inputFluids('gtceu:treated_light_naquadria_fuel 36000','gtceu:treated_heavy_naquadria_fuel 18000', 'gtceu:neutronium 1000', 'gtceu:enriched_naquadria_fuel_base 5000')
        .outputFluids('gtceu:naquadria_fuel_mixture_mk2 60000')
        .circuit(21)
        .duration(50*20)
        .EUt(GTValues.VA[GTValues.UHV])
	 event.recipes.gtceu.chemical_plant('naquadriafuelmixturemk3')
		.notConsumable('kubejs:chemical_tier_four')
        .inputFluids('gtceu:treated_light_naquadria_fuel 36000','gtceu:treated_heavy_naquadria_fuel 54000', 'gtceu:treated_super_dense_naquadria_fuel 30000', 'gtceu:enriched_naquadria_fuel_base 30000')
        .outputFluids('gtceu:naquadria_fuel_mixture_mk3 150000')
        .circuit(21)
        .duration(50*20)
        .EUt(GTValues.VA[GTValues.UEV])
	event.recipes.gtceu.atomiccompressor('naquadriafuelmk2')
		.itemInputs('kubejs:quantum_energy_capsule')
		.inputFluids('gtceu:naquadria_fuel_mixture_mk2 60000')
		.outputFluids('gtceu:naquadria_fuel_mk2 10000')
		.duration(500)
		.EUt(GTValues.VA[GTValues.UHV]);
	event.recipes.gtceu.atomiccompressor('naquadriafuelmk3')
		.itemInputs('kubejs:quantum_energy_capsule')
		.inputFluids('gtceu:naquadria_fuel_mixture_mk3 150000')
		.outputFluids('gtceu:naquadria_fuel_mk3 20000')
		.duration(500)
		.EUt(GTValues.VA[GTValues.UEV]);
		
		//Fuel Wastes
		 event.recipes.gtceu.centrifuge('naquadriamk3fuelwaste')
        .inputFluids('gtceu:naquadria_mk3_fuel_waste 50000')
        .itemOutputsRanged('gtceu:thorium_dust', 500, 700)
        .itemOutputsRanged('gtceu:plutonium_241_dust', 90, 140)
        .itemOutputsRanged('gtceu:teslarium_dust', 35, 80)
        .outputFluids('gtceu:naquadria 30000', 'gtceu:antimatter 25000')
	    .cleanroom(CleanroomType.STERILE_CLEANROOM)
        .duration(1000)
        .EUt((GTValues.VA[GTValues.UEV]))
		 event.recipes.gtceu.centrifuge('naquadriamk2fuelwaste')
        .inputFluids('gtceu:naquadria_mk2_fuel_waste 50000')
        .itemOutputsRanged('gtceu:thorium_dust', 300, 450)
        .itemOutputsRanged('gtceu:plutonium_241_dust', 90, 170)
        .outputFluids('gtceu:naquadria 20000')
		.cleanroom(CleanroomType.CLEANROOM)
        .duration(1000)
        .EUt((GTValues.VA[GTValues.UHV]))
		event.recipes.gtceu.centrifuge('naquadriamk1fuelwaste')
        .inputFluids('gtceu:naquadria_mk1_fuel_waste 50000')
        .itemOutputsRanged('gtceu:thorium_dust', 150, 200)
        .outputFluids('gtceu:naquadria 2500')
		.cleanroom(CleanroomType.CLEANROOM)
        .duration(1000)
        .EUt((GTValues.VA[GTValues.UV]))

})
