GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('high_pressure_reactor')
        .category('drack')
        .setEUIO('in')
        .setMaxIOSize(1, 2, 1, 2)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.BATH)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('large_high_pressure_reactor', 'multiblock')
        .recipeType('high_pressure_reactor')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock('kubejs:highly_reinforced_radioactive_casing'))
        .pattern(definition => FactoryBlockPattern.start()
			.aisle("BBBAAACCCCCCCCC", "BDBAAACCCCCCCCC", "BDBAAACCCCCCCCC", "BDBAAACCCCCCCCC", "BDBAAACCCCCCCCC", "BDBAAACCCCCCCCC", "BDBAAACCCCCCCCC", "BDBAAACCCCCCCCC", "BBBAAACCCCCCCCC", "AAAAAAACCCCCCCA")
			.aisle("BBBAAACCCCCCCCC", "DEBAAACEEEEEEEC", "DEEEEEEEFFEFFEC", "DEBAAACEFFEFFEC", "DEEEEEEEEEEEEEC", "DEBAAACEFFEFFEC", "DEEEEEEEFFEFFEC", "DEBAAACEEEEEEEC", "BDBAAACCCCCCCCC", "AAAAAAACCCCCCCA")
			.aisle("BBBAAACCCCCCCCC", "BEBAAACEEEEEEEC", "BEBAAACEGGGGGEC", "BEBAAACEGGGGGEC", "BEBAAACEGGGGGEC", "BEBAAACEGGGGGEC", "BEBAAACEGGGGGEC", "BEBAAACEEEEEEEC", "BDBAAACCCCCCCCC", "AAAAAAACCCCCCCA")
			.aisle("BBBAAACCCCCCCCC", "DEBAAACEFFEFFEC", "DEEEEEEFGGGGGFC", "DEBAAACFGGGGGFC", "DEEEEEEEGGGGGEC", "DEBAAACFGGGGGFC", "DEEEEEEFGGGGGFC", "DEBAAACEFFEFFEC", "BDBAAACCCCCCCCC", "AAAAAAACCCCCCCA")
			.aisle("BBBAAACCCCCCCCC", "BEBAAACEFFEFFEC", "BEBAAACFGGGGGFC", "BEBAAACFGGGGGFC", "BEBAAACEGGGGGEC", "BEBAAACFGGGGGFC", "BEBAAACFGGGGGFC", "BEBAAACEFFEFFEC", "BDBAAACCCCCCCCC", "AAAAAAACCCCCCCA")
			.aisle("BBBAAACCCCCCCCC", "DEBAAACEEEEEEEC", "DEEEEEEEGGGGGEC", "DEBAAACEGGGGGEC", "DEEEEEEEGGGGGEC", "DEBAAACEGGGGGEC", "DEEEEEEEGGGGGEC", "DEBAAACEEEEEEEC", "BDBAAACCCCCCCCC", "AAAAAAACCCCCCCA")
			.aisle("BBBAAACCCCCCCCC", "BDBAAACCCCCCCCC", "BDBAAACCGGGGGCC", "BDBAAACCGGGGGCC", "BDBAAACCGGGGGCC", "BDBAAACCGGGGGCC", "BDBAAACCGGGGGCC", "BDBAAACCCCCCCCC", "BBBAAACCCCCCCCC", "AAAAAAAAAAAAAAA")
			.aisle("AAAAAAACCCCCCCA", "AAAAAAACCCHCCCA", "AAAAAAACIIIIICA", "AAAAAAACIIIIICA", "AAAAAAACIIIIICA", "AAAAAAACIIIIICA", "AAAAAAACIIIIICA", "AAAAAAACCCCCCCA", "AAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAA")
   .where("A", Predicates.any())
   .where("B", Predicates.blocks("gtceu:corrosion_proof_casing"))
   .where("C", Predicates.blocks("kubejs:highly_reinforced_radioactive_casing")
			.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
			.or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
			.or(Predicates.abilities(PartAbility.EXPORT_ITEMS, PartAbility.EXPORT_FLUIDS, PartAbility.INPUT_ENERGY, PartAbility.IMPORT_FLUIDS, PartAbility.IMPORT_ITEMS)))
   .where("D", Predicates.blocks("gtceu:extreme_engine_intake_casing"))
   .where("E", Predicates.blocks("kubejs:osmiridium_pipe_casing"))
   .where("F", Predicates.blocks("gtceu:assembly_line_grating"))
   .where("G", Predicates.blocks("minecraft:air"))
   .where("H", Predicates.controller(Predicates.blocks(definition.get())))
   .where("I", Predicates.blocks("gtceu:laminated_glass"))
            .build())
        .workableCasingModel("kubejs:block/casings/highly_reinforced_radioactive_casing", 'gtceu:block/multiblock/generator/large_plasma_turbine')})