GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('rock_crusher')
        .category('drack')
        .setEUIO('in')
        .setMaxIOSize(2, 2, 0, 0)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.MACERATOR)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('tectonic_plate_accelerator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('rock_crusher')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.MACHINE_CASING_IV)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCCC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CCCCCCC')
            .aisle('CCCCCCC', 'CIIPMMC', 'CIIPMMC', 'CIIPMMC', 'CCCCCCC')
            .aisle('CCCCCCC', 'CIIRMMC', 'CIIRMMC', 'CIIRMMC', 'CCCCCCC')
            .aisle('CCCKCCC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CCCCCCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('G', Predicates.blocks('gtceu:laminated_glass'))
            .where('P', Predicates.blocks('kubejs:osmiridium_pipe_casing'))
            .where('I', Predicates.blocks('minecraft:blue_ice'))
            .where('M', Predicates.blocks('minecraft:magma_block'))
            .where('R', Predicates.blocks('gtceu:red_granite'))
            .where('C', Predicates.blocks('gtceu:heatproof_machine_casing')
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS, PartAbility.EXPORT_FLUIDS, PartAbility.IMPORT_ITEMS, PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY)))
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_heatproof', 'gtceu:block/machines/rock_crusher')   
})