ServerEvents.recipes(event => {

    event.recipes.gtceu.dimensional_miner('asteroid_mining_1')
    .inputFluids([Fluid.of('gtceu:eternity', 5)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('7500x gtceu:raw_cosmic_iridium')
    .itemOutputs('7500x gtceu:raw_cosmic_osmium')
    .itemOutputs('7500x gtceu:raw_cosmic_tungsten')
    .itemOutputs('7500x gtceu:raw_cosmic_titanium')
    .itemOutputs('7500x gtceu:raw_cosmic_neutronium')
    .circuit(1)
    .duration(20*20)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);

    event.recipes.gtceu.dimensional_miner('asteroid_mining_2')
    .inputFluids([Fluid.of('gtceu:eternity', 5)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('75000x gtceu:raw_kaemite')
    .itemOutputs('75000x gtceu:raw_resonant_naquadah')
    .itemOutputs('75000x gtceu:raw_resonant_essence')
    .circuit(2)
    .dimension('sogcore:asteroid_belt')
    .duration(20*20)
    .EUt(GTValues.VA[GTValues.UIV]);

    event.recipes.gtceu.dimensional_miner('asteroid_mining_3')
    .inputFluids([Fluid.of('gtceu:eternity', 5)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('75000x gtceu:raw_chaos')
    .itemOutputs('50000x gtceu:raw_draconium')
    .itemOutputs('7500x gtceu:raw_awakened_draconium')
    .itemOutputs('500x gtceu:raw_infinity_catalyst')
    .circuit(3)
    .duration(20*10)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);
    
    event.recipes.gtceu.dimensional_miner('asteroid_mining_3_2')
    .notConsumable('kubejs:dimensional_pump_module')
    .inputFluids([Fluid.of('gtceu:eternity', 5)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemOutputs('500x gtceu:raw_chaos')
    .itemOutputs('500x gtceu:raw_draconium')
    .itemOutputs('500x gtceu:raw_awakened_draconium')
    .itemOutputs('500x gtceu:raw_infinity_catalyst')
    .chancedFluidOutput('gtceu:stellar_matter_plasma 5000', 2500, 0)
    .chancedFluidOutput('gtceu:universium 2000', 1500, 0)
    .chancedFluidOutput('gtceu:molten_space_time 100', 1500, 0)
    .circuit(3)
    .duration(20*20)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);

    event.recipes.gtceu.dimensional_miner('asteroid_mining_4')
    .inputFluids([Fluid.of('gtceu:eternity', 500)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('1000000x gtceu:raw_draconium')
    .circuit(4)
    .duration(20*40)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);
    event.recipes.gtceu.dimensional_miner('asteroid_mining_5')
    .inputFluids([Fluid.of('gtceu:eternity', 500)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('1000000x gtceu:raw_chaos')
    .circuit(5)
    .duration(20*40)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);
})
