GTCEuStartupEvents.registry('gtceu:recipe_type', event => {

    event.create('processor_printing_factory_lv')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 4, 0) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
    event.create('processor_printing_factory_mv')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 4, 0) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
    event.create('processor_printing_factory_hv')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 4, 0) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
    event.create('processor_printing_factory_ev')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 4, 0) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
    event.create('processor_printing_factory_iv')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 4, 0) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
    event.create('processor_printing_factory_luv')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 4, 0) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
    event.create('processor_printing_factory_zpm')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 4, 0) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
    event.create('processor_printing_factory_uv')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 4, 0) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
     event.create('processor_printing_factory_uhv')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 1, 4, 0) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('processor_printing_factory_lv', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('processor_printing_factory_lv')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock('kubejs:neutronium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCC', 'GGGGGG', 'FFFFFF', '######')
            .aisle('OBBBBB', 'AAAAAA', 'HHHHHH', 'CCCCCC')
            .aisle('CCCCCC', 'GGGGGG', 'FFFFUK', '######')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('B', Predicates.blocks('gtceu:me_stocking_input_bus')
                    .or(Predicates.blocks('gtceu:ulv_input_bus'))
                )
                .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
                .where('F', Predicates.blocks('gtceu:sterilizing_filter_casing'))
                .where('A', Predicates.blocks('gtceu:assembly_line_unit'))
                .where('H', Predicates.blocks('gtceu:hypoxylon_frame'))
                .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .where('U', Predicates.blocks('gtceu:ulv_input_bus'))
                .where('C', Predicates.blocks('kubejs:neutronium_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY))
                )
                .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('kubejs:block/neutronium/ncasing', 'gtceu:block/multiblock/assembly_line')

    event.create('processor_printing_factory_mv', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('processor_printing_factory_mv')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock('kubejs:neutronium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCC', 'GGGGGG', 'FFFFFF', '######')
            .aisle('OBBBBB', 'AAAAAA', 'HHHHHH', 'CCCCCC')
            .aisle('CCCCCC', 'GGGGGG', 'FFFFUK', '######')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('B', Predicates.blocks('gtceu:me_stocking_input_bus')
                    .or(Predicates.blocks('gtceu:ulv_input_bus'))
                )
                .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
                .where('F', Predicates.blocks('gtceu:sterilizing_filter_casing'))
                .where('A', Predicates.blocks('gtceu:assembly_line_unit'))
                .where('H', Predicates.blocks('gtceu:hypoxylon_frame'))
                .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .where('U', Predicates.blocks('gtceu:ulv_input_bus'))
                .where('C', Predicates.blocks('kubejs:neutronium_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY))
                )
                .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('kubejs:block/neutronium/ncasing', 'gtceu:block/multiblock/assembly_line')

    event.create('processor_printing_factory_hv', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('processor_printing_factory_hv')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock('kubejs:neutronium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCC', 'GGGGGG', 'FFFFFF', '######')
            .aisle('OBBBBB', 'AAAAAA', 'HHHHHH', 'CCCCCC')
            .aisle('CCCCCC', 'GGGGGG', 'FFFFUK', '######')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('B', Predicates.blocks('gtceu:me_stocking_input_bus')
                    .or(Predicates.blocks('gtceu:ulv_input_bus'))
                )
                .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
                .where('F', Predicates.blocks('gtceu:sterilizing_filter_casing'))
                .where('A', Predicates.blocks('gtceu:assembly_line_unit'))
                .where('H', Predicates.blocks('gtceu:hypoxylon_frame'))
                .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .where('U', Predicates.blocks('gtceu:ulv_input_bus'))
                .where('C', Predicates.blocks('kubejs:neutronium_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY))
                )
                .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('kubejs:block/neutronium/ncasing', 'gtceu:block/multiblock/assembly_line')

    event.create('processor_printing_factory_ev', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('processor_printing_factory_ev')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock('kubejs:neutronium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCC', 'GGGGGG', 'FFFFFF', '######')
            .aisle('OBBBBB', 'AAAAAA', 'HHHHHH', 'CCCCCC')
            .aisle('CCCCCC', 'GGGGGG', 'FFFFUK', '######')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('B', Predicates.blocks('gtceu:me_stocking_input_bus')
                    .or(Predicates.blocks('gtceu:ulv_input_bus'))
                )
                .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
                .where('F', Predicates.blocks('gtceu:sterilizing_filter_casing'))
                .where('A', Predicates.blocks('gtceu:assembly_line_unit'))
                .where('H', Predicates.blocks('gtceu:hypoxylon_frame'))
                .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .where('U', Predicates.blocks('gtceu:ulv_input_bus'))
                .where('C', Predicates.blocks('kubejs:neutronium_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY))
                )
                .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('kubejs:block/neutronium/ncasing', 'gtceu:block/multiblock/assembly_line')

    event.create('processor_printing_factory_iv', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('processor_printing_factory_iv')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock('kubejs:neutronium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCC', 'GGGGGG', 'FFFFFF', '######')
            .aisle('OBBBBB', 'AAAAAA', 'HHHHHH', 'CCCCCC')
            .aisle('CCCCCC', 'GGGGGG', 'FFFFUK', '######')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('B', Predicates.blocks('gtceu:me_stocking_input_bus')
                    .or(Predicates.blocks('gtceu:ulv_input_bus'))
                )
                .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
                .where('F', Predicates.blocks('gtceu:sterilizing_filter_casing'))
                .where('A', Predicates.blocks('gtceu:assembly_line_unit'))
                .where('H', Predicates.blocks('gtceu:hypoxylon_frame'))
                .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .where('U', Predicates.blocks('gtceu:ulv_input_bus'))
                .where('C', Predicates.blocks('kubejs:neutronium_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY))
                )
                .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('kubejs:block/neutronium/ncasing', 'gtceu:block/multiblock/assembly_line')

    event.create('processor_printing_factory_luv', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('processor_printing_factory_luv')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock('kubejs:neutronium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCC', 'GGGGGG', 'FFFFFF', '######')
            .aisle('OBBBBB', 'AAAAAA', 'HHHHHH', 'CCCCCC')
            .aisle('CCCCCC', 'GGGGGG', 'FFFFUK', '######')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('B', Predicates.blocks('gtceu:me_stocking_input_bus')
                    .or(Predicates.blocks('gtceu:ulv_input_bus'))
                )
                .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
                .where('F', Predicates.blocks('gtceu:sterilizing_filter_casing'))
                .where('A', Predicates.blocks('gtceu:assembly_line_unit'))
                .where('H', Predicates.blocks('gtceu:hypoxylon_frame'))
                .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .where('U', Predicates.blocks('gtceu:ulv_input_bus'))
                .where('C', Predicates.blocks('kubejs:neutronium_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY))
                )
                .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('kubejs:block/neutronium/ncasing', 'gtceu:block/multiblock/assembly_line')

    event.create('processor_printing_factory_zpm', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('processor_printing_factory_zpm')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock('kubejs:neutronium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCC', 'GGGGGG', 'FFFFFF', '######')
            .aisle('OBBBBB', 'AAAAAA', 'HHHHHH', 'CCCCCC')
            .aisle('CCCCCC', 'GGGGGG', 'FFFFUK', '######')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('B', Predicates.blocks('gtceu:me_stocking_input_bus')
                    .or(Predicates.blocks('gtceu:ulv_input_bus'))
                )
                .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
                .where('F', Predicates.blocks('gtceu:sterilizing_filter_casing'))
                .where('A', Predicates.blocks('gtceu:assembly_line_unit'))
                .where('H', Predicates.blocks('gtceu:hypoxylon_frame'))
                .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .where('U', Predicates.blocks('gtceu:ulv_input_bus'))
                .where('C', Predicates.blocks('kubejs:neutronium_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY))
                )
                .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('kubejs:block/neutronium/ncasing', 'gtceu:block/multiblock/assembly_line')

    event.create('processor_printing_factory_uv', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('processor_printing_factory_uv')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock('kubejs:neutronium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCC', 'GGGGGG', 'FFFFFF', '######')
            .aisle('OBBBBB', 'AAAAAA', 'HHHHHH', 'CCCCCC')
            .aisle('CCCCCC', 'GGGGGG', 'FFFFUK', '######')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('B', Predicates.blocks('gtceu:me_stocking_input_bus')
                    .or(Predicates.blocks('gtceu:ulv_input_bus'))
                )
                .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
                .where('F', Predicates.blocks('gtceu:sterilizing_filter_casing'))
                .where('A', Predicates.blocks('gtceu:assembly_line_unit'))
                .where('H', Predicates.blocks('gtceu:hypoxylon_frame'))
                .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .where('U', Predicates.blocks('gtceu:ulv_input_bus'))
                .where('C', Predicates.blocks('kubejs:neutronium_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY))
                )
                .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('kubejs:block/neutronium/ncasing', 'gtceu:block/multiblock/assembly_line')

    event.create('processor_printing_factory_uhv', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('processor_printing_factory_uhv')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(() => Block.getBlock('kubejs:neutronium_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCC', 'GGGGGG', 'FFFFFF', '######')
            .aisle('OBBBBB', 'AAAAAA', 'HHHHHH', 'CCCCCC')
            .aisle('CCCCCC', 'GGGGGG', 'FFFFUK', '######')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('B', Predicates.blocks('gtceu:me_stocking_input_bus')
                    .or(Predicates.blocks('gtceu:ulv_input_bus'))
                )
                .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
                .where('F', Predicates.blocks('gtceu:sterilizing_filter_casing'))
                .where('A', Predicates.blocks('gtceu:assembly_line_unit'))
                .where('H', Predicates.blocks('gtceu:hypoxylon_frame'))
                .where('O', Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .where('U', Predicates.blocks('gtceu:ulv_input_bus'))
                .where('C', Predicates.blocks('kubejs:neutronium_casing')
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS, PartAbility.INPUT_ENERGY))
                )
                .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('kubejs:block/neutronium/ncasing', 'gtceu:block/multiblock/assembly_line')
})