ServerEvents.recipes(event => {

    event.recipes.gtceu.processor_printing_factory_lv('lv_circuits')
        .itemInputs('32x gtceu:plastic_printed_circuit_board', '4x gtceu:soc_wafer', '8x #forge:ingots/tin', '8x #forge:ingots/copper')
        .notConsumable('kubejs:lv_circuit_etching_pattern')
        .inputFluids('gtceu:lubricant 1500', 'gtceu:soldering_alloy 2304')
        .itemOutputs('192x gtceu:microchip_processor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.ZPM])
    event.recipes.gtceu.processor_printing_factory_mv('mv_circuits')
        .itemInputs('16x gtceu:plastic_printed_circuit_board', '2x gtceu:soc_wafer', '8x gtceu:red_alloy_ingot', '8x gtceu:annealed_copper_ingot')
        .notConsumable('kubejs:mv_circuit_etching_pattern')
        .inputFluids('gtceu:lubricant 750', 'gtceu:soldering_alloy 1152')
        .itemOutputs('64x gtceu:micro_processor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.ZPM])    
    event.recipes.gtceu.processor_printing_factory_hv('hv_circuits')
        .itemInputs('16x gtceu:epoxy_printed_circuit_board', '2x gtceu:advanced_soc_wafer', '8x gtceu:platinum_ingot', '8x gtceu:electrum_ingot')
        .notConsumable('kubejs:hv_circuit_etching_pattern')
        .inputFluids('gtceu:lubricant 750', 'gtceu:soldering_alloy 1152')
        .itemOutputs('64x gtceu:nano_processor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UV])
    event.recipes.gtceu.processor_printing_factory_ev('ev_circuits')
        .itemInputs('16x gtceu:fiber_reinforced_printed_circuit_board', '2x gtceu:advanced_soc_wafer', '24x gtceu:platinum_ingot', '16x gtceu:niobium_titanium_ingot')
        .notConsumable('kubejs:ev_circuit_etching_pattern')
        .inputFluids('gtceu:lubricant 750', 'gtceu:soldering_alloy 1152')
        .itemOutputs('64x gtceu:quantum_processor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UV])
    event.recipes.gtceu.processor_printing_factory_iv('iv_circuits')
        .itemInputs('16x gtceu:multilayer_fiber_reinforced_printed_circuit_board', '16x gtceu:crystal_soc', '16x gtceu:yttrium_barium_cuprate_ingot', '16x gtceu:niobium_titanium_ingot')
        .notConsumable('kubejs:iv_circuit_etching_pattern')
        .inputFluids('gtceu:lubricant 750', 'gtceu:soldering_alloy 1152')
        .itemOutputs('64x gtceu:crystal_processor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UHV])
    event.recipes.gtceu.processor_printing_factory_luv('luv_circuits')
        .itemInputs('16x gtceu:wetware_printed_circuit_board', 'gtceu:iv_sensor', '32x gtceu:stem_cells', '2x gtceu:highly_advanced_soc_wafer', '16x gtceu:yttrium_barium_cuprate_ingot', '16x gtceu:naquadah_ingot')
        .notConsumable('kubejs:luv_circuit_etching_pattern')
        .inputFluids('gtceu:lubricant 750', 'gtceu:soldering_alloy 1152')
        .itemOutputs('64x gtceu:wetware_processor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UHV])
    event.recipes.gtceu.processor_printing_factory_zpm('zpm_circuits')
        .itemInputs('16x kubejs:highly_resonative_printed_circuit_board', '32x gtceu:wetware_processor', '32x gtceu:hsss_ingot', '256x gtceu:resonant_essence_ingot', '256x gtceu:kaemite_ingot', '4x kubejs:extremely_advanced_soc_wafer')
        .notConsumable('kubejs:zpm_circuit_etching_pattern')
        .inputFluids('gtceu:lubricant 1000', 'gtceu:soldering_alloy 36864', 'gtceu:polybenzimidazole 50688')
        .inputFluids([Fluid.of('gtceu:condensed_star_matter 259968')])
        .itemOutputs('64x kubejs:resonant_processor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UEV])
    event.recipes.gtceu.processor_printing_factory_uv('uv_circuits')
        .itemInputs('16x kubejs:dragon_infused_neuro_processing_unit', '32x kubejs:resonant_processor', '256x avaritia:neutron_ingot', '256x draconicevolution:draconium_ingot', '4x kubejs:extremely_advanced_soc_wafer', '32x avaritia:eternal_singularity', '32x kubejs:quantum_data_module')
        .notConsumable('kubejs:uv_circuit_etching_pattern')
        .inputFluids('gtceu:stropharic_hypoxylon 4000', 'gtceu:soldering_alloy 36864', 'gtceu:polybenzimidazole 50688')
        .inputFluids([Fluid.of('gtceu:condensed_star_matter 259968')])
        .itemOutputs('64x kubejs:dragon_processor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UIV])
    event.recipes.gtceu.processor_printing_factory_uhv('uhv_circuits')
        .itemInputs('16x kubejs:cosmic_printed_circuit_board', '32x kubejs:dragon_processor', '120x gtceu:pure_cosmic_matter_ingot', '768x draconicevolution:awakened_draconium_ingot', '4x kubejs:extremely_advanced_soc_wafer', '512x avaritia:eternal_singularity', '32x kubejs:quantum_data_module')
        .notConsumable('kubejs:uhv_circuit_etching_pattern')
        .inputFluids('gtceu:hypoxylon 259968', 'gtceu:antimatter 259968', 'gtceu:astral_flux_plasma 2304', 'gtceu:eternity 320')
        .itemOutputs('64x kubejs:cosmic_processor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UXV])

    //controller recipes
    event.recipes.gtceu.assembly_line('processor_printing_factory_lv')
        .itemInputs('gtceu:large_circuit_assembler', 'gtceu:large_cutter', '8x gtceu:cosmic_iridium_frame', '2x gtceu:uev_robot_arm', '2x gtceu:uev_conveyor_module', '4x #gtceu:circuits/uev', 'kubejs:lv_circuit_etching_pattern')
        .inputFluids('gtceu:soldering_alloy 9216', 'gtceu:pcb_coolant 1500', 'gtceu:hypoxylon 2304')
        .itemOutputs('gtceu:processor_printing_factory_lv')
        .duration(1500)
        .EUt(GTValues.VA[GTValues.UIV])
    event.recipes.gtceu.assembler('processor_printing_factory_mv')
        .itemInputs('gtceu:processor_printing_factory_lv', 'kubejs:mv_circuit_etching_pattern')
        .inputFluids('gtceu:soldering_alloy 2304')
        .itemOutputs('gtceu:processor_printing_factory_mv')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UEV])
    event.recipes.gtceu.assembler('processor_printing_factory_hv')
        .itemInputs('gtceu:processor_printing_factory_mv', 'kubejs:hv_circuit_etching_pattern')
        .inputFluids('gtceu:soldering_alloy 2304')
        .itemOutputs('gtceu:processor_printing_factory_hv')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UEV])
    event.recipes.gtceu.assembler('processor_printing_factory_ev')
        .itemInputs('gtceu:processor_printing_factory_hv', 'kubejs:ev_circuit_etching_pattern')
        .inputFluids('gtceu:soldering_alloy 2304')
        .itemOutputs('gtceu:processor_printing_factory_ev')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UEV])
    event.recipes.gtceu.assembler('processor_printing_factory_iv')
        .itemInputs('gtceu:processor_printing_factory_ev', 'kubejs:iv_circuit_etching_pattern')
        .inputFluids('gtceu:soldering_alloy 2304')
        .itemOutputs('gtceu:processor_printing_factory_iv')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UEV])
    event.recipes.gtceu.assembler('processor_printing_factory_luv')
        .itemInputs('gtceu:processor_printing_factory_iv', 'kubejs:luv_circuit_etching_pattern')
        .inputFluids('gtceu:soldering_alloy 2304')
        .itemOutputs('gtceu:processor_printing_factory_luv')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UEV])
    event.recipes.gtceu.assembler('processor_printing_factory_zpm')
        .itemInputs('gtceu:processor_printing_factory_luv', 'kubejs:zpm_circuit_etching_pattern')
        .inputFluids('gtceu:soldering_alloy 2304')
        .itemOutputs('gtceu:processor_printing_factory_zpm')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UEV])
    event.recipes.gtceu.assembler('processor_printing_factory_uv')
        .itemInputs('gtceu:processor_printing_factory_zpm', 'kubejs:uv_circuit_etching_pattern')
        .inputFluids('gtceu:soldering_alloy 2304')
        .itemOutputs('gtceu:processor_printing_factory_uv')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UEV])
    event.recipes.gtceu.assembler('processor_printing_factory_uhv')
        .itemInputs('gtceu:processor_printing_factory_uv', 'kubejs:uhv_circuit_etching_pattern')
        .inputFluids('gtceu:soldering_alloy 2304')
        .itemOutputs('gtceu:processor_printing_factory_uhv')
        .duration(200)
        .EUt(GTValues.VA[GTValues.UEV])

    //Printed circuit recipes
    event.recipes.gtceu.laser_engraver('lv_circuit_etching_pattern')
        .itemInputs('64x #gtceu:circuits/lv')
        .notConsumable('#forge:lenses/red')
        .itemOutputs('kubejs:lv_circuit_etching_pattern')
        .duration(900)
        .EUt(GTValues.VA[GTValues.UHV])
    event.recipes.gtceu.laser_engraver('mv_circuit_etching_pattern')
        .itemInputs('64x #gtceu:circuits/mv')
        .itemOutputs('kubejs:mv_circuit_etching_pattern')
        .notConsumable('#forge:lenses/red')
        .duration(900)
        .EUt(GTValues.VA[GTValues.UHV])
    event.recipes.gtceu.laser_engraver('hv_circuit_etching_pattern')
        .itemInputs('64x #gtceu:circuits/hv')
        .notConsumable('#forge:lenses/red')
        .itemOutputs('kubejs:hv_circuit_etching_pattern')
        .duration(900)
        .EUt(GTValues.VA[GTValues.UHV])
    event.recipes.gtceu.laser_engraver('ev_circuit_etching_pattern')
        .itemInputs('64x #gtceu:circuits/ev')
        .itemOutputs('kubejs:ev_circuit_etching_pattern')
        .notConsumable('#forge:lenses/red')
        .duration(900)
        .EUt(GTValues.VA[GTValues.UHV])
    event.recipes.gtceu.laser_engraver('iv_circuit_etching_pattern')
        .itemInputs('64x #gtceu:circuits/iv')
        .itemOutputs('kubejs:iv_circuit_etching_pattern')
        .notConsumable('#forge:lenses/red')
        .duration(900)
        .EUt(GTValues.VA[GTValues.UHV])
    event.recipes.gtceu.laser_engraver('luv_circuit_etching_pattern')
        .itemInputs('64x #gtceu:circuits/luv')
        .itemOutputs('kubejs:luv_circuit_etching_pattern')
        .notConsumable('#forge:lenses/red')
        .duration(900)
        .EUt(GTValues.VA[GTValues.UHV])
    event.recipes.gtceu.laser_engraver('zpm_circuit_etching_pattern')
        .itemInputs('64x #gtceu:circuits/uhv')
        .itemOutputs('kubejs:zpm_circuit_etching_pattern')
        .notConsumable('#forge:lenses/red')
        .duration(900)
        .EUt(GTValues.VA[GTValues.UIV])
    event.recipes.gtceu.laser_engraver('uv_circuit_etching_pattern')
        .itemInputs('64x #gtceu:circuits/uev')
        .itemOutputs('kubejs:uv_circuit_etching_pattern')
        .notConsumable('#forge:lenses/red')
        .duration(900)
        .EUt(GTValues.VA[GTValues.UXV])
    event.recipes.gtceu.laser_engraver('uhv_circuit_etching_pattern')
        .itemInputs('64x #gtceu:circuits/uiv')
        .itemOutputs('kubejs:uhv_circuit_etching_pattern')
        .notConsumable('#forge:lenses/red')
        .duration(900)
        .EUt(GTValues.VA[GTValues.OpV])
})